# Generated by Django 3.0.8 on 2020-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogbuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
    ]
