# Generated by Django 3.0.8 on 2020-08-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogbuster',
        ),
    ]
