# Generated by Django 3.0.8 on 2020-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roumanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description1', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image1', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image2', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image3', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image4', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image5', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image6', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image7', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image8', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image9', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('image0', models.ImageField(blank=True, upload_to='Roumanie/images/')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
    ]
